[project]
name = "luckpaint"
title = "luckpaint"
version = "0.4"
authors = ["Rabia Alhaffar"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "2.17"
edition = "pro"

[dependencies]

[itch]
url = "https://rabios.itch.io/luckpaint"
# Your username on Itch.io.
username = "rabios"
